apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "stock-charts.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts }}
      secretName: {{ template "stock-charts.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "stock-charts.fullname" . }}
                port:
                  name: http
