apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{- include "stock-charts.name" . }}
    helm.sh/chart: {{- include "stock-charts.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{- include "stock-charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
