replicaCount: 1

image:
  repository: gcr.io/devopss-task/shopfront
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: shop-front
  type: ClusterIP
  port: 8010

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: example.com
      paths: ['/']
  tls:
    - secretName: shop-front-tls
      hosts:
        - example.com
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}