replicaCount: 1

image:
  repository: gcr.io/devopss-task/stockmanager
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: stock-manager
  type: ClusterIP
  port: 8030

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: example.com
      paths: ['/']
  tls:
    - secretName: stock-manager-tls
      hosts:
        - example.com
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}